### ISSUE TITLE
Crash when using file: url scheme

### ISSUE THREAD

**Issue by sloat** [Guutong/cordova-plugin-android-native-pdfviewer#3]
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-128664
                  Process: com.fdsa.fdsa, PID: 27527
                  java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
                      at xyz.guutong.androidpdfviewer.Utils.DownloadFileUrlConnectionImpl$1.run(DownloadFileUrlConnectionImpl.java:41)
                      at java.lang.Thread.run(Thread.java:818)
```

**Comment by Guutong** [comment]
@sloat do you have example code?
this plugin current version support http url only

**Comment by telepriest** [comment]
@Guutong  do you have an update on this issue or is there a workaround you know about?
thank you

**Comment by richie50** [comment]
Yes do you know please?
